/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: radarscene_new.proto/radarscene_new-a9c395e9014541306db375aaca1fb888.proto */

#ifndef PROTOBUF_C_radarscene_5fnew_2eproto_2fradarscene_5fnew_2da9c395e9014541306db375aaca1fb888_2eproto__INCLUDED
#define PROTOBUF_C_radarscene_5fnew_2eproto_2fradarscene_5fnew_2da9c395e9014541306db375aaca1fb888_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Radar__BoundingBox Radar__BoundingBox;
typedef struct Radar__Point Radar__Point;
typedef struct Radar__Polygon Radar__Polygon;
typedef struct Radar__Velocity Radar__Velocity;
typedef struct Radar__Covariance Radar__Covariance;
typedef struct Radar__Label Radar__Label;
typedef struct Radar__Labels Radar__Labels;
typedef struct Radar__GeoPosition Radar__GeoPosition;
typedef struct Radar__Orientation Radar__Orientation;
typedef struct Radar__Object Radar__Object;
typedef struct Radar__Event Radar__Event;
typedef struct Radar__Failure Radar__Failure;
typedef struct Radar__Status Radar__Status;
typedef struct Radar__Scene Radar__Scene;
typedef struct Radar__Scenes Radar__Scenes;


/* --- enums --- */

/*
 **
 * Event action used by an event. See further info below.
 */
typedef enum _Radar__EventAction {
  RADAR__EVENT_ACTION__EVENT_DELETE = 0,
  RADAR__EVENT_ACTION__EVENT_SPLIT = 1,
  RADAR__EVENT_ACTION__EVENT_MERGE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__EVENT_ACTION)
} Radar__EventAction;

/* --- messages --- */

/*
 **
 * Bounding box describes an object's surrounding
 * rectangle with the upper left and lower right corners.
 */
struct  Radar__BoundingBox
{
  ProtobufCMessage base;
  float left;
  float top;
  float right;
  float bottom;
};
#define RADAR__BOUNDING_BOX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__bounding_box__descriptor) \
    , 0, 0, 0, 0 }


typedef enum {
  RADAR__POINT__HAS_Z__NOT_SET = 0,
  RADAR__POINT__HAS_Z_Z = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__POINT__HAS_Z__CASE)
} Radar__Point__HasZCase;

/*
 **
 * A point or coordinate, could be represented in 2D or 3D
 * depending of the producer. Check has_z's status.
 */
struct  Radar__Point
{
  ProtobufCMessage base;
  float x;
  float y;
  Radar__Point__HasZCase has_z_case;
  union {
    float z;
  };
};
#define RADAR__POINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__point__descriptor) \
    , 0, 0, RADAR__POINT__HAS_Z__NOT_SET, {0} }


/*
 **
 * A polygon describes the surrounding shape of an object with points.
 */
struct  Radar__Polygon
{
  ProtobufCMessage base;
  size_t n_points;
  Radar__Point **points;
};
#define RADAR__POLYGON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__polygon__descriptor) \
    , 0,NULL }


typedef enum {
  RADAR__VELOCITY__HAS_VZ__NOT_SET = 0,
  RADAR__VELOCITY__HAS_VZ_VZ = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__VELOCITY__HAS_VZ__CASE)
} Radar__Velocity__HasVzCase;

/*
 **
 * Velocity coordinates, could be represented in 2D or 3D
 * depending of the producer. Check has_vz's status.
 */
struct  Radar__Velocity
{
  ProtobufCMessage base;
  float vx;
  float vy;
  Radar__Velocity__HasVzCase has_vz_case;
  union {
    float vz;
  };
};
#define RADAR__VELOCITY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__velocity__descriptor) \
    , 0, 0, RADAR__VELOCITY__HAS_VZ__NOT_SET, {0} }


/*
 **
 * Covariance matrix, describing the covariance between state variables of
 * interest.
 * As a covariance matrix, it is assumed to be square: the number of variables
 * can be taken to be the square root of the total number of elements in the
 * matrix.
 * Elements shall be packed in row-major order, i.e. given a matrix of size N,
 * the first N elements in this message describe the first row of the matrix.
 */
struct  Radar__Covariance
{
  ProtobufCMessage base;
  size_t n_elements;
  float *elements;
};
#define RADAR__COVARIANCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__covariance__descriptor) \
    , 0,NULL }


typedef enum {
  RADAR__LABEL__HAS_CLASS_ID__NOT_SET = 0,
  RADAR__LABEL__HAS_CLASS_ID_ID = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__LABEL__HAS_CLASS_ID__CASE)
} Radar__Label__HasClassIdCase;

typedef enum {
  RADAR__LABEL__HAS_CONFIDENCE__NOT_SET = 0,
  RADAR__LABEL__HAS_CONFIDENCE_CONFIDENCE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__LABEL__HAS_CONFIDENCE__CASE)
} Radar__Label__HasConfidenceCase;

typedef enum {
  RADAR__LABEL__HAS_NAME__NOT_SET = 0,
  RADAR__LABEL__HAS_NAME_NAME = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__LABEL__HAS_NAME__CASE)
} Radar__Label__HasNameCase;

/*
 **
 * Label is classification parameters.
 * A class is identified with an id.
 * The confidence value is a level describing how confident the
 * classification is.
 * The name is a nice name description of the class label.
 */
struct  Radar__Label
{
  ProtobufCMessage base;
  Radar__Label__HasClassIdCase has_class_id_case;
  union {
    uint32_t id;
  };
  Radar__Label__HasConfidenceCase has_confidence_case;
  union {
    float confidence;
  };
  Radar__Label__HasNameCase has_name_case;
  union {
    char *name;
  };
};
#define RADAR__LABEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__label__descriptor) \
    , RADAR__LABEL__HAS_CLASS_ID__NOT_SET, {0}, RADAR__LABEL__HAS_CONFIDENCE__NOT_SET, {0}, RADAR__LABEL__HAS_NAME__NOT_SET, {0} }


/*
 **
 * Labels is an array of labels.
 */
struct  Radar__Labels
{
  ProtobufCMessage base;
  size_t n_labels;
  Radar__Label **labels;
};
#define RADAR__LABELS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__labels__descriptor) \
    , 0,NULL }


typedef enum {
  RADAR__GEO_POSITION__HAS_DLAT__NOT_SET = 0,
  RADAR__GEO_POSITION__HAS_DLAT_DLAT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__GEO_POSITION__HAS_DLAT__CASE)
} Radar__GeoPosition__HasDlatCase;

typedef enum {
  RADAR__GEO_POSITION__HAS_DLON__NOT_SET = 0,
  RADAR__GEO_POSITION__HAS_DLON_DLON = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__GEO_POSITION__HAS_DLON__CASE)
} Radar__GeoPosition__HasDlonCase;

/*
 **
 * GeoPosition is a geographic position
 */
struct  Radar__GeoPosition
{
  ProtobufCMessage base;
  float elevation;
  float lat;
  float lon;
  Radar__GeoPosition__HasDlatCase has_dlat_case;
  union {
    double dlat;
  };
  Radar__GeoPosition__HasDlonCase has_dlon_case;
  union {
    double dlon;
  };
};
#define RADAR__GEO_POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__geo_position__descriptor) \
    , 0, 0, 0, RADAR__GEO_POSITION__HAS_DLAT__NOT_SET, {0}, RADAR__GEO_POSITION__HAS_DLON__NOT_SET, {0} }


/*
 **
 * Orientation of the device
 */
struct  Radar__Orientation
{
  ProtobufCMessage base;
  double tilt;
  double roll;
};
#define RADAR__ORIENTATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__orientation__descriptor) \
    , 0, 0 }


typedef enum {
  RADAR__OBJECT__HAS_OBJECT_ID__NOT_SET = 0,
  RADAR__OBJECT__HAS_OBJECT_ID_ID = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_OBJECT_ID__CASE)
} Radar__Object__HasObjectIdCase;

typedef enum {
  RADAR__OBJECT__HAS_CONFIDENCE__NOT_SET = 0,
  RADAR__OBJECT__HAS_CONFIDENCE_CONFIDENCE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_CONFIDENCE__CASE)
} Radar__Object__HasConfidenceCase;

typedef enum {
  RADAR__OBJECT__HAS_LABELS__NOT_SET = 0,
  RADAR__OBJECT__HAS_LABELS_LABELS = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_LABELS__CASE)
} Radar__Object__HasLabelsCase;

typedef enum {
  RADAR__OBJECT__HAS_BOUNDINGBOX__NOT_SET = 0,
  RADAR__OBJECT__HAS_BOUNDINGBOX_BOUNDING_BOX = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_BOUNDINGBOX__CASE)
} Radar__Object__HasBoundingboxCase;

typedef enum {
  RADAR__OBJECT__HAS_POLYGON__NOT_SET = 0,
  RADAR__OBJECT__HAS_POLYGON_POLYGON = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_POLYGON__CASE)
} Radar__Object__HasPolygonCase;

typedef enum {
  RADAR__OBJECT__HAS_VELOCITY__NOT_SET = 0,
  RADAR__OBJECT__HAS_VELOCITY_VELOCITY = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_VELOCITY__CASE)
} Radar__Object__HasVelocityCase;

typedef enum {
  RADAR__OBJECT__HAS_POSITION__NOT_SET = 0,
  RADAR__OBJECT__HAS_POSITION_POSITION = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_POSITION__CASE)
} Radar__Object__HasPositionCase;

typedef enum {
  RADAR__OBJECT__HAS_AREA__NOT_SET = 0,
  RADAR__OBJECT__HAS_AREA_AREA = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_AREA__CASE)
} Radar__Object__HasAreaCase;

typedef enum {
  RADAR__OBJECT__HAS_COVARIANCE__NOT_SET = 0,
  RADAR__OBJECT__HAS_COVARIANCE_COVARIANCE = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_COVARIANCE__CASE)
} Radar__Object__HasCovarianceCase;

typedef enum {
  RADAR__OBJECT__HAS_VELOCITY3D__NOT_SET = 0,
  RADAR__OBJECT__HAS_VELOCITY3D_VELOCITY3D = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_VELOCITY3D__CASE)
} Radar__Object__HasVelocity3dCase;

typedef enum {
  RADAR__OBJECT__HAS_GEOPOSITION__NOT_SET = 0,
  RADAR__OBJECT__HAS_GEOPOSITION_GEOPOSITION = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__OBJECT__HAS_GEOPOSITION__CASE)
} Radar__Object__HasGeopositionCase;

/*
 **
 * Object represents an analytic detection.
 * It contains identifier, class label information and
 * geometric representations.
 * The producer sets the status of each property when it is
 * is produced, this is the reason for the oneof declaration.
 */
struct  Radar__Object
{
  ProtobufCMessage base;
  Radar__Object__HasObjectIdCase has_object_id_case;
  union {
    uint32_t id;
  };
  Radar__Object__HasConfidenceCase has_confidence_case;
  union {
    float confidence;
  };
  Radar__Object__HasLabelsCase has_labels_case;
  union {
    Radar__Labels *labels;
  };
  Radar__Object__HasBoundingboxCase has_boundingbox_case;
  union {
    Radar__BoundingBox *bounding_box;
  };
  Radar__Object__HasPolygonCase has_polygon_case;
  union {
    Radar__Polygon *polygon;
  };
  Radar__Object__HasVelocityCase has_velocity_case;
  union {
    Radar__Velocity *velocity;
  };
  Radar__Object__HasPositionCase has_position_case;
  union {
    Radar__Point *position;
  };
  Radar__Object__HasAreaCase has_area_case;
  union {
    float area;
  };
  Radar__Object__HasCovarianceCase has_covariance_case;
  union {
    Radar__Covariance *covariance;
  };
  Radar__Object__HasVelocity3dCase has_velocity3d_case;
  union {
    Radar__Velocity *velocity3d;
  };
  Radar__Object__HasGeopositionCase has_geoposition_case;
  union {
    Radar__GeoPosition *geoposition;
  };
};
#define RADAR__OBJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__object__descriptor) \
    , RADAR__OBJECT__HAS_OBJECT_ID__NOT_SET, {0}, RADAR__OBJECT__HAS_CONFIDENCE__NOT_SET, {0}, RADAR__OBJECT__HAS_LABELS__NOT_SET, {0}, RADAR__OBJECT__HAS_BOUNDINGBOX__NOT_SET, {0}, RADAR__OBJECT__HAS_POLYGON__NOT_SET, {0}, RADAR__OBJECT__HAS_VELOCITY__NOT_SET, {0}, RADAR__OBJECT__HAS_POSITION__NOT_SET, {0}, RADAR__OBJECT__HAS_AREA__NOT_SET, {0}, RADAR__OBJECT__HAS_COVARIANCE__NOT_SET, {0}, RADAR__OBJECT__HAS_VELOCITY3D__NOT_SET, {0}, RADAR__OBJECT__HAS_GEOPOSITION__NOT_SET, {0} }


/*
 **
 * Event is an object that holds information about an event. The type
 * of event is specified with an action and refers to one or multiple
 * object ids.
 * For example a delete event only has one id, so the object_id refers
 * to the object that has been deleted (and object_ids is empty).
 * For a split event the object_id is the source id and the object_ids
 * are the target ids, i.e. one id is split into multiple ids.
 * For a merge event the object_ids are the source id and the object_id
 * is the target id, i.e. multiple ids are merged into one id.
 */
struct  Radar__Event
{
  ProtobufCMessage base;
  /*
   * Event identifier 
   */
  Radar__EventAction action;
  /*
   * Object's id this event refer to 
   */
  int32_t object_id;
  /*
   * Multiple object ids if needed 
   */
  size_t n_object_ids;
  int32_t *object_ids;
};
#define RADAR__EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__event__descriptor) \
    , RADAR__EVENT_ACTION__EVENT_DELETE, 0, 0,NULL }


/*
 **
 * Failure describes a single failure and its state.
 */
struct  Radar__Failure
{
  ProtobufCMessage base;
  char *name;
  int32_t id;
  protobuf_c_boolean state;
};
#define RADAR__FAILURE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__failure__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


/*
 **
 * Status describes the radar status.
 */
struct  Radar__Status
{
  ProtobufCMessage base;
  protobuf_c_boolean enabled;
  protobuf_c_boolean prerecorded;
  size_t n_failures;
  Radar__Failure **failures;
};
#define RADAR__STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__status__descriptor) \
    , 0, 0, 0,NULL }


typedef enum {
  RADAR__SCENE__HAS_TIME__NOT_SET = 0,
  RADAR__SCENE__HAS_TIME_TIME = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__SCENE__HAS_TIME__CASE)
} Radar__Scene__HasTimeCase;

typedef enum {
  RADAR__SCENE__HAS_REAL_TIME__NOT_SET = 0,
  RADAR__SCENE__HAS_REAL_TIME_REAL_TIME = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__SCENE__HAS_REAL_TIME__CASE)
} Radar__Scene__HasRealTimeCase;

typedef enum {
  RADAR__SCENE__HAS_STATUS__NOT_SET = 0,
  RADAR__SCENE__HAS_STATUS_STATUS = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__SCENE__HAS_STATUS__CASE)
} Radar__Scene__HasStatusCase;

typedef enum {
  RADAR__SCENE__HAS_ORIENTATION__NOT_SET = 0,
  RADAR__SCENE__HAS_ORIENTATION_ORIENTATION = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__SCENE__HAS_ORIENTATION__CASE)
} Radar__Scene__HasOrientationCase;

typedef enum {
  RADAR__SCENE__HAS_PARAM_CHANGED__NOT_SET = 0,
  RADAR__SCENE__HAS_PARAM_CHANGED_PARAM_CHANGED = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RADAR__SCENE__HAS_PARAM_CHANGED__CASE)
} Radar__Scene__HasParamChangedCase;

/*
 **
 * Scene object is a time-frame representation of analytic objects.
 * The objects limits, normalisation, orientation should be given by
 * documentation from the current provider.
 * Examples:
 * The orientation may be a cartesian coordinate system or
 * coordinates are accessed as pixels from an image or spherical
 * coordinates system describing depth and angles.
 */
struct  Radar__Scene
{
  ProtobufCMessage base;
  /*
   * Objects 
   */
  size_t n_objects;
  Radar__Object **objects;
  /*
   * Events 
   */
  size_t n_events;
  Radar__Event **events;
  Radar__Scene__HasTimeCase has_time_case;
  union {
    uint64_t time;
  };
  Radar__Scene__HasRealTimeCase has_real_time_case;
  union {
    uint64_t real_time;
  };
  Radar__Scene__HasStatusCase has_status_case;
  union {
    Radar__Status *status;
  };
  Radar__Scene__HasOrientationCase has_orientation_case;
  union {
    Radar__Orientation *orientation;
  };
  Radar__Scene__HasParamChangedCase has_param_changed_case;
  union {
    protobuf_c_boolean param_changed;
  };
};
#define RADAR__SCENE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__scene__descriptor) \
    , 0,NULL, 0,NULL, RADAR__SCENE__HAS_TIME__NOT_SET, {0}, RADAR__SCENE__HAS_REAL_TIME__NOT_SET, {0}, RADAR__SCENE__HAS_STATUS__NOT_SET, {0}, RADAR__SCENE__HAS_ORIENTATION__NOT_SET, {0}, RADAR__SCENE__HAS_PARAM_CHANGED__NOT_SET, {0} }


/*
 **
 * Scenes object hold a number of scene objects.
 */
struct  Radar__Scenes
{
  ProtobufCMessage base;
  size_t n_scenes;
  Radar__Scene **scenes;
};
#define RADAR__SCENES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&radar__scenes__descriptor) \
    , 0,NULL }


/* Radar__BoundingBox methods */
void   radar__bounding_box__init
                     (Radar__BoundingBox         *message);
size_t radar__bounding_box__get_packed_size
                     (const Radar__BoundingBox   *message);
size_t radar__bounding_box__pack
                     (const Radar__BoundingBox   *message,
                      uint8_t             *out);
size_t radar__bounding_box__pack_to_buffer
                     (const Radar__BoundingBox   *message,
                      ProtobufCBuffer     *buffer);
Radar__BoundingBox *
       radar__bounding_box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__bounding_box__free_unpacked
                     (Radar__BoundingBox *message,
                      ProtobufCAllocator *allocator);
/* Radar__Point methods */
void   radar__point__init
                     (Radar__Point         *message);
size_t radar__point__get_packed_size
                     (const Radar__Point   *message);
size_t radar__point__pack
                     (const Radar__Point   *message,
                      uint8_t             *out);
size_t radar__point__pack_to_buffer
                     (const Radar__Point   *message,
                      ProtobufCBuffer     *buffer);
Radar__Point *
       radar__point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__point__free_unpacked
                     (Radar__Point *message,
                      ProtobufCAllocator *allocator);
/* Radar__Polygon methods */
void   radar__polygon__init
                     (Radar__Polygon         *message);
size_t radar__polygon__get_packed_size
                     (const Radar__Polygon   *message);
size_t radar__polygon__pack
                     (const Radar__Polygon   *message,
                      uint8_t             *out);
size_t radar__polygon__pack_to_buffer
                     (const Radar__Polygon   *message,
                      ProtobufCBuffer     *buffer);
Radar__Polygon *
       radar__polygon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__polygon__free_unpacked
                     (Radar__Polygon *message,
                      ProtobufCAllocator *allocator);
/* Radar__Velocity methods */
void   radar__velocity__init
                     (Radar__Velocity         *message);
size_t radar__velocity__get_packed_size
                     (const Radar__Velocity   *message);
size_t radar__velocity__pack
                     (const Radar__Velocity   *message,
                      uint8_t             *out);
size_t radar__velocity__pack_to_buffer
                     (const Radar__Velocity   *message,
                      ProtobufCBuffer     *buffer);
Radar__Velocity *
       radar__velocity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__velocity__free_unpacked
                     (Radar__Velocity *message,
                      ProtobufCAllocator *allocator);
/* Radar__Covariance methods */
void   radar__covariance__init
                     (Radar__Covariance         *message);
size_t radar__covariance__get_packed_size
                     (const Radar__Covariance   *message);
size_t radar__covariance__pack
                     (const Radar__Covariance   *message,
                      uint8_t             *out);
size_t radar__covariance__pack_to_buffer
                     (const Radar__Covariance   *message,
                      ProtobufCBuffer     *buffer);
Radar__Covariance *
       radar__covariance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__covariance__free_unpacked
                     (Radar__Covariance *message,
                      ProtobufCAllocator *allocator);
/* Radar__Label methods */
void   radar__label__init
                     (Radar__Label         *message);
size_t radar__label__get_packed_size
                     (const Radar__Label   *message);
size_t radar__label__pack
                     (const Radar__Label   *message,
                      uint8_t             *out);
size_t radar__label__pack_to_buffer
                     (const Radar__Label   *message,
                      ProtobufCBuffer     *buffer);
Radar__Label *
       radar__label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__label__free_unpacked
                     (Radar__Label *message,
                      ProtobufCAllocator *allocator);
/* Radar__Labels methods */
void   radar__labels__init
                     (Radar__Labels         *message);
size_t radar__labels__get_packed_size
                     (const Radar__Labels   *message);
size_t radar__labels__pack
                     (const Radar__Labels   *message,
                      uint8_t             *out);
size_t radar__labels__pack_to_buffer
                     (const Radar__Labels   *message,
                      ProtobufCBuffer     *buffer);
Radar__Labels *
       radar__labels__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__labels__free_unpacked
                     (Radar__Labels *message,
                      ProtobufCAllocator *allocator);
/* Radar__GeoPosition methods */
void   radar__geo_position__init
                     (Radar__GeoPosition         *message);
size_t radar__geo_position__get_packed_size
                     (const Radar__GeoPosition   *message);
size_t radar__geo_position__pack
                     (const Radar__GeoPosition   *message,
                      uint8_t             *out);
size_t radar__geo_position__pack_to_buffer
                     (const Radar__GeoPosition   *message,
                      ProtobufCBuffer     *buffer);
Radar__GeoPosition *
       radar__geo_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__geo_position__free_unpacked
                     (Radar__GeoPosition *message,
                      ProtobufCAllocator *allocator);
/* Radar__Orientation methods */
void   radar__orientation__init
                     (Radar__Orientation         *message);
size_t radar__orientation__get_packed_size
                     (const Radar__Orientation   *message);
size_t radar__orientation__pack
                     (const Radar__Orientation   *message,
                      uint8_t             *out);
size_t radar__orientation__pack_to_buffer
                     (const Radar__Orientation   *message,
                      ProtobufCBuffer     *buffer);
Radar__Orientation *
       radar__orientation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__orientation__free_unpacked
                     (Radar__Orientation *message,
                      ProtobufCAllocator *allocator);
/* Radar__Object methods */
void   radar__object__init
                     (Radar__Object         *message);
size_t radar__object__get_packed_size
                     (const Radar__Object   *message);
size_t radar__object__pack
                     (const Radar__Object   *message,
                      uint8_t             *out);
size_t radar__object__pack_to_buffer
                     (const Radar__Object   *message,
                      ProtobufCBuffer     *buffer);
Radar__Object *
       radar__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__object__free_unpacked
                     (Radar__Object *message,
                      ProtobufCAllocator *allocator);
/* Radar__Event methods */
void   radar__event__init
                     (Radar__Event         *message);
size_t radar__event__get_packed_size
                     (const Radar__Event   *message);
size_t radar__event__pack
                     (const Radar__Event   *message,
                      uint8_t             *out);
size_t radar__event__pack_to_buffer
                     (const Radar__Event   *message,
                      ProtobufCBuffer     *buffer);
Radar__Event *
       radar__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__event__free_unpacked
                     (Radar__Event *message,
                      ProtobufCAllocator *allocator);
/* Radar__Failure methods */
void   radar__failure__init
                     (Radar__Failure         *message);
size_t radar__failure__get_packed_size
                     (const Radar__Failure   *message);
size_t radar__failure__pack
                     (const Radar__Failure   *message,
                      uint8_t             *out);
size_t radar__failure__pack_to_buffer
                     (const Radar__Failure   *message,
                      ProtobufCBuffer     *buffer);
Radar__Failure *
       radar__failure__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__failure__free_unpacked
                     (Radar__Failure *message,
                      ProtobufCAllocator *allocator);
/* Radar__Status methods */
void   radar__status__init
                     (Radar__Status         *message);
size_t radar__status__get_packed_size
                     (const Radar__Status   *message);
size_t radar__status__pack
                     (const Radar__Status   *message,
                      uint8_t             *out);
size_t radar__status__pack_to_buffer
                     (const Radar__Status   *message,
                      ProtobufCBuffer     *buffer);
Radar__Status *
       radar__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__status__free_unpacked
                     (Radar__Status *message,
                      ProtobufCAllocator *allocator);
/* Radar__Scene methods */
void   radar__scene__init
                     (Radar__Scene         *message);
size_t radar__scene__get_packed_size
                     (const Radar__Scene   *message);
size_t radar__scene__pack
                     (const Radar__Scene   *message,
                      uint8_t             *out);
size_t radar__scene__pack_to_buffer
                     (const Radar__Scene   *message,
                      ProtobufCBuffer     *buffer);
Radar__Scene *
       radar__scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__scene__free_unpacked
                     (Radar__Scene *message,
                      ProtobufCAllocator *allocator);
/* Radar__Scenes methods */
void   radar__scenes__init
                     (Radar__Scenes         *message);
size_t radar__scenes__get_packed_size
                     (const Radar__Scenes   *message);
size_t radar__scenes__pack
                     (const Radar__Scenes   *message,
                      uint8_t             *out);
size_t radar__scenes__pack_to_buffer
                     (const Radar__Scenes   *message,
                      ProtobufCBuffer     *buffer);
Radar__Scenes *
       radar__scenes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   radar__scenes__free_unpacked
                     (Radar__Scenes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Radar__BoundingBox_Closure)
                 (const Radar__BoundingBox *message,
                  void *closure_data);
typedef void (*Radar__Point_Closure)
                 (const Radar__Point *message,
                  void *closure_data);
typedef void (*Radar__Polygon_Closure)
                 (const Radar__Polygon *message,
                  void *closure_data);
typedef void (*Radar__Velocity_Closure)
                 (const Radar__Velocity *message,
                  void *closure_data);
typedef void (*Radar__Covariance_Closure)
                 (const Radar__Covariance *message,
                  void *closure_data);
typedef void (*Radar__Label_Closure)
                 (const Radar__Label *message,
                  void *closure_data);
typedef void (*Radar__Labels_Closure)
                 (const Radar__Labels *message,
                  void *closure_data);
typedef void (*Radar__GeoPosition_Closure)
                 (const Radar__GeoPosition *message,
                  void *closure_data);
typedef void (*Radar__Orientation_Closure)
                 (const Radar__Orientation *message,
                  void *closure_data);
typedef void (*Radar__Object_Closure)
                 (const Radar__Object *message,
                  void *closure_data);
typedef void (*Radar__Event_Closure)
                 (const Radar__Event *message,
                  void *closure_data);
typedef void (*Radar__Failure_Closure)
                 (const Radar__Failure *message,
                  void *closure_data);
typedef void (*Radar__Status_Closure)
                 (const Radar__Status *message,
                  void *closure_data);
typedef void (*Radar__Scene_Closure)
                 (const Radar__Scene *message,
                  void *closure_data);
typedef void (*Radar__Scenes_Closure)
                 (const Radar__Scenes *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    radar__event_action__descriptor;
extern const ProtobufCMessageDescriptor radar__bounding_box__descriptor;
extern const ProtobufCMessageDescriptor radar__point__descriptor;
extern const ProtobufCMessageDescriptor radar__polygon__descriptor;
extern const ProtobufCMessageDescriptor radar__velocity__descriptor;
extern const ProtobufCMessageDescriptor radar__covariance__descriptor;
extern const ProtobufCMessageDescriptor radar__label__descriptor;
extern const ProtobufCMessageDescriptor radar__labels__descriptor;
extern const ProtobufCMessageDescriptor radar__geo_position__descriptor;
extern const ProtobufCMessageDescriptor radar__orientation__descriptor;
extern const ProtobufCMessageDescriptor radar__object__descriptor;
extern const ProtobufCMessageDescriptor radar__event__descriptor;
extern const ProtobufCMessageDescriptor radar__failure__descriptor;
extern const ProtobufCMessageDescriptor radar__status__descriptor;
extern const ProtobufCMessageDescriptor radar__scene__descriptor;
extern const ProtobufCMessageDescriptor radar__scenes__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_radarscene_5fnew_2eproto_2fradarscene_5fnew_2da9c395e9014541306db375aaca1fb888_2eproto__INCLUDED */
