/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: radarscene_new.proto/radarscene_new-a9c395e9014541306db375aaca1fb888.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "radarscene.pb-c.h"
void   radar__bounding_box__init
                     (Radar__BoundingBox         *message)
{
  static const Radar__BoundingBox init_value = RADAR__BOUNDING_BOX__INIT;
  *message = init_value;
}
size_t radar__bounding_box__get_packed_size
                     (const Radar__BoundingBox *message)
{
  assert(message->base.descriptor == &radar__bounding_box__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__bounding_box__pack
                     (const Radar__BoundingBox *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__bounding_box__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__bounding_box__pack_to_buffer
                     (const Radar__BoundingBox *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__bounding_box__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__BoundingBox *
       radar__bounding_box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__BoundingBox *)
     protobuf_c_message_unpack (&radar__bounding_box__descriptor,
                                allocator, len, data);
}
void   radar__bounding_box__free_unpacked
                     (Radar__BoundingBox *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__bounding_box__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__point__init
                     (Radar__Point         *message)
{
  static const Radar__Point init_value = RADAR__POINT__INIT;
  *message = init_value;
}
size_t radar__point__get_packed_size
                     (const Radar__Point *message)
{
  assert(message->base.descriptor == &radar__point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__point__pack
                     (const Radar__Point *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__point__pack_to_buffer
                     (const Radar__Point *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Point *
       radar__point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Point *)
     protobuf_c_message_unpack (&radar__point__descriptor,
                                allocator, len, data);
}
void   radar__point__free_unpacked
                     (Radar__Point *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__polygon__init
                     (Radar__Polygon         *message)
{
  static const Radar__Polygon init_value = RADAR__POLYGON__INIT;
  *message = init_value;
}
size_t radar__polygon__get_packed_size
                     (const Radar__Polygon *message)
{
  assert(message->base.descriptor == &radar__polygon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__polygon__pack
                     (const Radar__Polygon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__polygon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__polygon__pack_to_buffer
                     (const Radar__Polygon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__polygon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Polygon *
       radar__polygon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Polygon *)
     protobuf_c_message_unpack (&radar__polygon__descriptor,
                                allocator, len, data);
}
void   radar__polygon__free_unpacked
                     (Radar__Polygon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__polygon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__velocity__init
                     (Radar__Velocity         *message)
{
  static const Radar__Velocity init_value = RADAR__VELOCITY__INIT;
  *message = init_value;
}
size_t radar__velocity__get_packed_size
                     (const Radar__Velocity *message)
{
  assert(message->base.descriptor == &radar__velocity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__velocity__pack
                     (const Radar__Velocity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__velocity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__velocity__pack_to_buffer
                     (const Radar__Velocity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__velocity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Velocity *
       radar__velocity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Velocity *)
     protobuf_c_message_unpack (&radar__velocity__descriptor,
                                allocator, len, data);
}
void   radar__velocity__free_unpacked
                     (Radar__Velocity *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__velocity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__covariance__init
                     (Radar__Covariance         *message)
{
  static const Radar__Covariance init_value = RADAR__COVARIANCE__INIT;
  *message = init_value;
}
size_t radar__covariance__get_packed_size
                     (const Radar__Covariance *message)
{
  assert(message->base.descriptor == &radar__covariance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__covariance__pack
                     (const Radar__Covariance *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__covariance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__covariance__pack_to_buffer
                     (const Radar__Covariance *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__covariance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Covariance *
       radar__covariance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Covariance *)
     protobuf_c_message_unpack (&radar__covariance__descriptor,
                                allocator, len, data);
}
void   radar__covariance__free_unpacked
                     (Radar__Covariance *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__covariance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__label__init
                     (Radar__Label         *message)
{
  static const Radar__Label init_value = RADAR__LABEL__INIT;
  *message = init_value;
}
size_t radar__label__get_packed_size
                     (const Radar__Label *message)
{
  assert(message->base.descriptor == &radar__label__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__label__pack
                     (const Radar__Label *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__label__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__label__pack_to_buffer
                     (const Radar__Label *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__label__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Label *
       radar__label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Label *)
     protobuf_c_message_unpack (&radar__label__descriptor,
                                allocator, len, data);
}
void   radar__label__free_unpacked
                     (Radar__Label *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__label__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__labels__init
                     (Radar__Labels         *message)
{
  static const Radar__Labels init_value = RADAR__LABELS__INIT;
  *message = init_value;
}
size_t radar__labels__get_packed_size
                     (const Radar__Labels *message)
{
  assert(message->base.descriptor == &radar__labels__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__labels__pack
                     (const Radar__Labels *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__labels__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__labels__pack_to_buffer
                     (const Radar__Labels *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__labels__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Labels *
       radar__labels__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Labels *)
     protobuf_c_message_unpack (&radar__labels__descriptor,
                                allocator, len, data);
}
void   radar__labels__free_unpacked
                     (Radar__Labels *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__labels__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__geo_position__init
                     (Radar__GeoPosition         *message)
{
  static const Radar__GeoPosition init_value = RADAR__GEO_POSITION__INIT;
  *message = init_value;
}
size_t radar__geo_position__get_packed_size
                     (const Radar__GeoPosition *message)
{
  assert(message->base.descriptor == &radar__geo_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__geo_position__pack
                     (const Radar__GeoPosition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__geo_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__geo_position__pack_to_buffer
                     (const Radar__GeoPosition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__geo_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__GeoPosition *
       radar__geo_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__GeoPosition *)
     protobuf_c_message_unpack (&radar__geo_position__descriptor,
                                allocator, len, data);
}
void   radar__geo_position__free_unpacked
                     (Radar__GeoPosition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__geo_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__orientation__init
                     (Radar__Orientation         *message)
{
  static const Radar__Orientation init_value = RADAR__ORIENTATION__INIT;
  *message = init_value;
}
size_t radar__orientation__get_packed_size
                     (const Radar__Orientation *message)
{
  assert(message->base.descriptor == &radar__orientation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__orientation__pack
                     (const Radar__Orientation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__orientation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__orientation__pack_to_buffer
                     (const Radar__Orientation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__orientation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Orientation *
       radar__orientation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Orientation *)
     protobuf_c_message_unpack (&radar__orientation__descriptor,
                                allocator, len, data);
}
void   radar__orientation__free_unpacked
                     (Radar__Orientation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__orientation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__object__init
                     (Radar__Object         *message)
{
  static const Radar__Object init_value = RADAR__OBJECT__INIT;
  *message = init_value;
}
size_t radar__object__get_packed_size
                     (const Radar__Object *message)
{
  assert(message->base.descriptor == &radar__object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__object__pack
                     (const Radar__Object *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__object__pack_to_buffer
                     (const Radar__Object *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Object *
       radar__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Object *)
     protobuf_c_message_unpack (&radar__object__descriptor,
                                allocator, len, data);
}
void   radar__object__free_unpacked
                     (Radar__Object *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__event__init
                     (Radar__Event         *message)
{
  static const Radar__Event init_value = RADAR__EVENT__INIT;
  *message = init_value;
}
size_t radar__event__get_packed_size
                     (const Radar__Event *message)
{
  assert(message->base.descriptor == &radar__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__event__pack
                     (const Radar__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__event__pack_to_buffer
                     (const Radar__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Event *
       radar__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Event *)
     protobuf_c_message_unpack (&radar__event__descriptor,
                                allocator, len, data);
}
void   radar__event__free_unpacked
                     (Radar__Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__failure__init
                     (Radar__Failure         *message)
{
  static const Radar__Failure init_value = RADAR__FAILURE__INIT;
  *message = init_value;
}
size_t radar__failure__get_packed_size
                     (const Radar__Failure *message)
{
  assert(message->base.descriptor == &radar__failure__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__failure__pack
                     (const Radar__Failure *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__failure__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__failure__pack_to_buffer
                     (const Radar__Failure *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__failure__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Failure *
       radar__failure__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Failure *)
     protobuf_c_message_unpack (&radar__failure__descriptor,
                                allocator, len, data);
}
void   radar__failure__free_unpacked
                     (Radar__Failure *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__failure__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__status__init
                     (Radar__Status         *message)
{
  static const Radar__Status init_value = RADAR__STATUS__INIT;
  *message = init_value;
}
size_t radar__status__get_packed_size
                     (const Radar__Status *message)
{
  assert(message->base.descriptor == &radar__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__status__pack
                     (const Radar__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__status__pack_to_buffer
                     (const Radar__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Status *
       radar__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Status *)
     protobuf_c_message_unpack (&radar__status__descriptor,
                                allocator, len, data);
}
void   radar__status__free_unpacked
                     (Radar__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__scene__init
                     (Radar__Scene         *message)
{
  static const Radar__Scene init_value = RADAR__SCENE__INIT;
  *message = init_value;
}
size_t radar__scene__get_packed_size
                     (const Radar__Scene *message)
{
  assert(message->base.descriptor == &radar__scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__scene__pack
                     (const Radar__Scene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__scene__pack_to_buffer
                     (const Radar__Scene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Scene *
       radar__scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Scene *)
     protobuf_c_message_unpack (&radar__scene__descriptor,
                                allocator, len, data);
}
void   radar__scene__free_unpacked
                     (Radar__Scene *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   radar__scenes__init
                     (Radar__Scenes         *message)
{
  static const Radar__Scenes init_value = RADAR__SCENES__INIT;
  *message = init_value;
}
size_t radar__scenes__get_packed_size
                     (const Radar__Scenes *message)
{
  assert(message->base.descriptor == &radar__scenes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t radar__scenes__pack
                     (const Radar__Scenes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &radar__scenes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t radar__scenes__pack_to_buffer
                     (const Radar__Scenes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &radar__scenes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Radar__Scenes *
       radar__scenes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Radar__Scenes *)
     protobuf_c_message_unpack (&radar__scenes__descriptor,
                                allocator, len, data);
}
void   radar__scenes__free_unpacked
                     (Radar__Scenes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &radar__scenes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor radar__bounding_box__field_descriptors[4] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__BoundingBox, left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "top",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__BoundingBox, top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__BoundingBox, right),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bottom",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__BoundingBox, bottom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__bounding_box__field_indices_by_name[] = {
  3,   /* field[3] = bottom */
  0,   /* field[0] = left */
  2,   /* field[2] = right */
  1,   /* field[1] = top */
};
static const ProtobufCIntRange radar__bounding_box__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor radar__bounding_box__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.BoundingBox",
  "BoundingBox",
  "Radar__BoundingBox",
  "Radar",
  sizeof(Radar__BoundingBox),
  4,
  radar__bounding_box__field_descriptors,
  radar__bounding_box__field_indices_by_name,
  1,  radar__bounding_box__number_ranges,
  (ProtobufCMessageInit) radar__bounding_box__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__point__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__Point, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__Point, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Radar__Point, has_z_case),
    offsetof(Radar__Point, z),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__point__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange radar__point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor radar__point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Point",
  "Point",
  "Radar__Point",
  "Radar",
  sizeof(Radar__Point),
  3,
  radar__point__field_descriptors,
  radar__point__field_indices_by_name,
  1,  radar__point__number_ranges,
  (ProtobufCMessageInit) radar__point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__polygon__field_descriptors[1] =
{
  {
    "points",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Polygon, n_points),
    offsetof(Radar__Polygon, points),
    &radar__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__polygon__field_indices_by_name[] = {
  0,   /* field[0] = points */
};
static const ProtobufCIntRange radar__polygon__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor radar__polygon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Polygon",
  "Polygon",
  "Radar__Polygon",
  "Radar",
  sizeof(Radar__Polygon),
  1,
  radar__polygon__field_descriptors,
  radar__polygon__field_indices_by_name,
  1,  radar__polygon__number_ranges,
  (ProtobufCMessageInit) radar__polygon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__velocity__field_descriptors[3] =
{
  {
    "vx",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__Velocity, vx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vy",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__Velocity, vy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vz",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Radar__Velocity, has_vz_case),
    offsetof(Radar__Velocity, vz),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__velocity__field_indices_by_name[] = {
  0,   /* field[0] = vx */
  1,   /* field[1] = vy */
  2,   /* field[2] = vz */
};
static const ProtobufCIntRange radar__velocity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor radar__velocity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Velocity",
  "Velocity",
  "Radar__Velocity",
  "Radar",
  sizeof(Radar__Velocity),
  3,
  radar__velocity__field_descriptors,
  radar__velocity__field_indices_by_name,
  1,  radar__velocity__number_ranges,
  (ProtobufCMessageInit) radar__velocity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__covariance__field_descriptors[1] =
{
  {
    "elements",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Radar__Covariance, n_elements),
    offsetof(Radar__Covariance, elements),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__covariance__field_indices_by_name[] = {
  0,   /* field[0] = elements */
};
static const ProtobufCIntRange radar__covariance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor radar__covariance__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Covariance",
  "Covariance",
  "Radar__Covariance",
  "Radar",
  sizeof(Radar__Covariance),
  1,
  radar__covariance__field_descriptors,
  radar__covariance__field_indices_by_name,
  1,  radar__covariance__number_ranges,
  (ProtobufCMessageInit) radar__covariance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__label__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Radar__Label, has_class_id_case),
    offsetof(Radar__Label, id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confidence",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Radar__Label, has_confidence_case),
    offsetof(Radar__Label, confidence),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Radar__Label, has_name_case),
    offsetof(Radar__Label, name),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__label__field_indices_by_name[] = {
  1,   /* field[1] = confidence */
  0,   /* field[0] = id */
  2,   /* field[2] = name */
};
static const ProtobufCIntRange radar__label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor radar__label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Label",
  "Label",
  "Radar__Label",
  "Radar",
  sizeof(Radar__Label),
  3,
  radar__label__field_descriptors,
  radar__label__field_indices_by_name,
  1,  radar__label__number_ranges,
  (ProtobufCMessageInit) radar__label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__labels__field_descriptors[1] =
{
  {
    "labels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Labels, n_labels),
    offsetof(Radar__Labels, labels),
    &radar__label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__labels__field_indices_by_name[] = {
  0,   /* field[0] = labels */
};
static const ProtobufCIntRange radar__labels__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor radar__labels__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Labels",
  "Labels",
  "Radar__Labels",
  "Radar",
  sizeof(Radar__Labels),
  1,
  radar__labels__field_descriptors,
  radar__labels__field_indices_by_name,
  1,  radar__labels__number_ranges,
  (ProtobufCMessageInit) radar__labels__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__geo_position__field_descriptors[5] =
{
  {
    "elevation",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__GeoPosition, elevation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__GeoPosition, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Radar__GeoPosition, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dlat",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Radar__GeoPosition, has_dlat_case),
    offsetof(Radar__GeoPosition, dlat),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dlon",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Radar__GeoPosition, has_dlon_case),
    offsetof(Radar__GeoPosition, dlon),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__geo_position__field_indices_by_name[] = {
  3,   /* field[3] = dlat */
  4,   /* field[4] = dlon */
  0,   /* field[0] = elevation */
  1,   /* field[1] = lat */
  2,   /* field[2] = lon */
};
static const ProtobufCIntRange radar__geo_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor radar__geo_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.GeoPosition",
  "GeoPosition",
  "Radar__GeoPosition",
  "Radar",
  sizeof(Radar__GeoPosition),
  5,
  radar__geo_position__field_descriptors,
  radar__geo_position__field_indices_by_name,
  1,  radar__geo_position__number_ranges,
  (ProtobufCMessageInit) radar__geo_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__orientation__field_descriptors[2] =
{
  {
    "tilt",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Radar__Orientation, tilt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Radar__Orientation, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__orientation__field_indices_by_name[] = {
  1,   /* field[1] = roll */
  0,   /* field[0] = tilt */
};
static const ProtobufCIntRange radar__orientation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor radar__orientation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Orientation",
  "Orientation",
  "Radar__Orientation",
  "Radar",
  sizeof(Radar__Orientation),
  2,
  radar__orientation__field_descriptors,
  radar__orientation__field_indices_by_name,
  1,  radar__orientation__number_ranges,
  (ProtobufCMessageInit) radar__orientation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__object__field_descriptors[11] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Radar__Object, has_object_id_case),
    offsetof(Radar__Object, id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confidence",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Radar__Object, has_confidence_case),
    offsetof(Radar__Object, confidence),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "labels",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_labels_case),
    offsetof(Radar__Object, labels),
    &radar__labels__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bounding_box",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_boundingbox_case),
    offsetof(Radar__Object, bounding_box),
    &radar__bounding_box__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "polygon",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_polygon_case),
    offsetof(Radar__Object, polygon),
    &radar__polygon__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_velocity_case),
    offsetof(Radar__Object, velocity),
    &radar__velocity__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_position_case),
    offsetof(Radar__Object, position),
    &radar__point__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "area",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Radar__Object, has_area_case),
    offsetof(Radar__Object, area),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "covariance",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_covariance_case),
    offsetof(Radar__Object, covariance),
    &radar__covariance__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity3d",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_velocity3d_case),
    offsetof(Radar__Object, velocity3d),
    &radar__velocity__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geoposition",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Object, has_geoposition_case),
    offsetof(Radar__Object, geoposition),
    &radar__geo_position__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__object__field_indices_by_name[] = {
  7,   /* field[7] = area */
  3,   /* field[3] = bounding_box */
  1,   /* field[1] = confidence */
  8,   /* field[8] = covariance */
  10,   /* field[10] = geoposition */
  0,   /* field[0] = id */
  2,   /* field[2] = labels */
  4,   /* field[4] = polygon */
  6,   /* field[6] = position */
  5,   /* field[5] = velocity */
  9,   /* field[9] = velocity3d */
};
static const ProtobufCIntRange radar__object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor radar__object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Object",
  "Object",
  "Radar__Object",
  "Radar",
  sizeof(Radar__Object),
  11,
  radar__object__field_descriptors,
  radar__object__field_indices_by_name,
  1,  radar__object__number_ranges,
  (ProtobufCMessageInit) radar__object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__event__field_descriptors[3] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Radar__Event, action),
    &radar__event_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Radar__Event, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_ids",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Radar__Event, n_object_ids),
    offsetof(Radar__Event, object_ids),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__event__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = object_id */
  2,   /* field[2] = object_ids */
};
static const ProtobufCIntRange radar__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor radar__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Event",
  "Event",
  "Radar__Event",
  "Radar",
  sizeof(Radar__Event),
  3,
  radar__event__field_descriptors,
  radar__event__field_indices_by_name,
  1,  radar__event__number_ranges,
  (ProtobufCMessageInit) radar__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__failure__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Radar__Failure, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Radar__Failure, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Radar__Failure, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__failure__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange radar__failure__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor radar__failure__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Failure",
  "Failure",
  "Radar__Failure",
  "Radar",
  sizeof(Radar__Failure),
  3,
  radar__failure__field_descriptors,
  radar__failure__field_indices_by_name,
  1,  radar__failure__number_ranges,
  (ProtobufCMessageInit) radar__failure__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__status__field_descriptors[3] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Radar__Status, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prerecorded",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Radar__Status, prerecorded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failures",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Status, n_failures),
    offsetof(Radar__Status, failures),
    &radar__failure__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__status__field_indices_by_name[] = {
  0,   /* field[0] = enabled */
  2,   /* field[2] = failures */
  1,   /* field[1] = prerecorded */
};
static const ProtobufCIntRange radar__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor radar__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Status",
  "Status",
  "Radar__Status",
  "Radar",
  sizeof(Radar__Status),
  3,
  radar__status__field_descriptors,
  radar__status__field_indices_by_name,
  1,  radar__status__number_ranges,
  (ProtobufCMessageInit) radar__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__scene__field_descriptors[7] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Radar__Scene, has_time_case),
    offsetof(Radar__Scene, time),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "real_time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Radar__Scene, has_real_time_case),
    offsetof(Radar__Scene, real_time),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "objects",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Scene, n_objects),
    offsetof(Radar__Scene, objects),
    &radar__object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Scene, n_events),
    offsetof(Radar__Scene, events),
    &radar__event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Scene, has_status_case),
    offsetof(Radar__Scene, status),
    &radar__status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orientation",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Scene, has_orientation_case),
    offsetof(Radar__Scene, orientation),
    &radar__orientation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "param_changed",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Radar__Scene, has_param_changed_case),
    offsetof(Radar__Scene, param_changed),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__scene__field_indices_by_name[] = {
  3,   /* field[3] = events */
  2,   /* field[2] = objects */
  5,   /* field[5] = orientation */
  6,   /* field[6] = param_changed */
  1,   /* field[1] = real_time */
  4,   /* field[4] = status */
  0,   /* field[0] = time */
};
static const ProtobufCIntRange radar__scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor radar__scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Scene",
  "Scene",
  "Radar__Scene",
  "Radar",
  sizeof(Radar__Scene),
  7,
  radar__scene__field_descriptors,
  radar__scene__field_indices_by_name,
  1,  radar__scene__number_ranges,
  (ProtobufCMessageInit) radar__scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor radar__scenes__field_descriptors[1] =
{
  {
    "scenes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Radar__Scenes, n_scenes),
    offsetof(Radar__Scenes, scenes),
    &radar__scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned radar__scenes__field_indices_by_name[] = {
  0,   /* field[0] = scenes */
};
static const ProtobufCIntRange radar__scenes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor radar__scenes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Radar.Scenes",
  "Scenes",
  "Radar__Scenes",
  "Radar",
  sizeof(Radar__Scenes),
  1,
  radar__scenes__field_descriptors,
  radar__scenes__field_indices_by_name,
  1,  radar__scenes__number_ranges,
  (ProtobufCMessageInit) radar__scenes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue radar__event_action__enum_values_by_number[3] =
{
  { "EVENT_DELETE", "RADAR__EVENT_ACTION__EVENT_DELETE", 0 },
  { "EVENT_SPLIT", "RADAR__EVENT_ACTION__EVENT_SPLIT", 1 },
  { "EVENT_MERGE", "RADAR__EVENT_ACTION__EVENT_MERGE", 2 },
};
static const ProtobufCIntRange radar__event_action__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex radar__event_action__enum_values_by_name[3] =
{
  { "EVENT_DELETE", 0 },
  { "EVENT_MERGE", 2 },
  { "EVENT_SPLIT", 1 },
};
const ProtobufCEnumDescriptor radar__event_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Radar.EventAction",
  "EventAction",
  "Radar__EventAction",
  "Radar",
  3,
  radar__event_action__enum_values_by_number,
  3,
  radar__event_action__enum_values_by_name,
  1,
  radar__event_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
