/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: video-object-detection 1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "video_object_detection.pb-c.h"
void   vod__attribute__init
                     (VOD__Attribute         *message)
{
  static const VOD__Attribute init_value = VOD__ATTRIBUTE__INIT;
  *message = init_value;
}
size_t vod__attribute__get_packed_size
                     (const VOD__Attribute *message)
{
  assert(message->base.descriptor == &vod__attribute__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__attribute__pack
                     (const VOD__Attribute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__attribute__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__attribute__pack_to_buffer
                     (const VOD__Attribute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__attribute__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Attribute *
       vod__attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Attribute *)
     protobuf_c_message_unpack (&vod__attribute__descriptor,
                                allocator, len, data);
}
void   vod__attribute__free_unpacked
                     (VOD__Attribute *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__attribute__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__classification__init
                     (VOD__Classification         *message)
{
  static const VOD__Classification init_value = VOD__CLASSIFICATION__INIT;
  *message = init_value;
}
size_t vod__classification__get_packed_size
                     (const VOD__Classification *message)
{
  assert(message->base.descriptor == &vod__classification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__classification__pack
                     (const VOD__Classification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__classification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__classification__pack_to_buffer
                     (const VOD__Classification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__classification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Classification *
       vod__classification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Classification *)
     protobuf_c_message_unpack (&vod__classification__descriptor,
                                allocator, len, data);
}
void   vod__classification__free_unpacked
                     (VOD__Classification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__classification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__detection__init
                     (VOD__Detection         *message)
{
  static const VOD__Detection init_value = VOD__DETECTION__INIT;
  *message = init_value;
}
size_t vod__detection__get_packed_size
                     (const VOD__Detection *message)
{
  assert(message->base.descriptor == &vod__detection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__detection__pack
                     (const VOD__Detection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__detection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__detection__pack_to_buffer
                     (const VOD__Detection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__detection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Detection *
       vod__detection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Detection *)
     protobuf_c_message_unpack (&vod__detection__descriptor,
                                allocator, len, data);
}
void   vod__detection__free_unpacked
                     (VOD__Detection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__detection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__event__init
                     (VOD__Event         *message)
{
  static const VOD__Event init_value = VOD__EVENT__INIT;
  *message = init_value;
}
size_t vod__event__get_packed_size
                     (const VOD__Event *message)
{
  assert(message->base.descriptor == &vod__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__event__pack
                     (const VOD__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__event__pack_to_buffer
                     (const VOD__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Event *
       vod__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Event *)
     protobuf_c_message_unpack (&vod__event__descriptor,
                                allocator, len, data);
}
void   vod__event__free_unpacked
                     (VOD__Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__scene__init
                     (VOD__Scene         *message)
{
  static const VOD__Scene init_value = VOD__SCENE__INIT;
  *message = init_value;
}
size_t vod__scene__get_packed_size
                     (const VOD__Scene *message)
{
  assert(message->base.descriptor == &vod__scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__scene__pack
                     (const VOD__Scene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__scene__pack_to_buffer
                     (const VOD__Scene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Scene *
       vod__scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Scene *)
     protobuf_c_message_unpack (&vod__scene__descriptor,
                                allocator, len, data);
}
void   vod__scene__free_unpacked
                     (VOD__Scene *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__calibration__init
                     (VOD__Calibration         *message)
{
  static const VOD__Calibration init_value = VOD__CALIBRATION__INIT;
  *message = init_value;
}
size_t vod__calibration__get_packed_size
                     (const VOD__Calibration *message)
{
  assert(message->base.descriptor == &vod__calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__calibration__pack
                     (const VOD__Calibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__calibration__pack_to_buffer
                     (const VOD__Calibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Calibration *
       vod__calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Calibration *)
     protobuf_c_message_unpack (&vod__calibration__descriptor,
                                allocator, len, data);
}
void   vod__calibration__free_unpacked
                     (VOD__Calibration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__object_class__init
                     (VOD__ObjectClass         *message)
{
  static const VOD__ObjectClass init_value = VOD__OBJECT_CLASS__INIT;
  *message = init_value;
}
size_t vod__object_class__get_packed_size
                     (const VOD__ObjectClass *message)
{
  assert(message->base.descriptor == &vod__object_class__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__object_class__pack
                     (const VOD__ObjectClass *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__object_class__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__object_class__pack_to_buffer
                     (const VOD__ObjectClass *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__object_class__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__ObjectClass *
       vod__object_class__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__ObjectClass *)
     protobuf_c_message_unpack (&vod__object_class__descriptor,
                                allocator, len, data);
}
void   vod__object_class__free_unpacked
                     (VOD__ObjectClass *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__object_class__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__attribute_class__init
                     (VOD__AttributeClass         *message)
{
  static const VOD__AttributeClass init_value = VOD__ATTRIBUTE_CLASS__INIT;
  *message = init_value;
}
size_t vod__attribute_class__get_packed_size
                     (const VOD__AttributeClass *message)
{
  assert(message->base.descriptor == &vod__attribute_class__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__attribute_class__pack
                     (const VOD__AttributeClass *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__attribute_class__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__attribute_class__pack_to_buffer
                     (const VOD__AttributeClass *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__attribute_class__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__AttributeClass *
       vod__attribute_class__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__AttributeClass *)
     protobuf_c_message_unpack (&vod__attribute_class__descriptor,
                                allocator, len, data);
}
void   vod__attribute_class__free_unpacked
                     (VOD__AttributeClass *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__attribute_class__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__attribute_type__init
                     (VOD__AttributeType         *message)
{
  static const VOD__AttributeType init_value = VOD__ATTRIBUTE_TYPE__INIT;
  *message = init_value;
}
size_t vod__attribute_type__get_packed_size
                     (const VOD__AttributeType *message)
{
  assert(message->base.descriptor == &vod__attribute_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__attribute_type__pack
                     (const VOD__AttributeType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__attribute_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__attribute_type__pack_to_buffer
                     (const VOD__AttributeType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__attribute_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__AttributeType *
       vod__attribute_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__AttributeType *)
     protobuf_c_message_unpack (&vod__attribute_type__descriptor,
                                allocator, len, data);
}
void   vod__attribute_type__free_unpacked
                     (VOD__AttributeType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__attribute_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__detector_information__init
                     (VOD__DetectorInformation         *message)
{
  static const VOD__DetectorInformation init_value = VOD__DETECTOR_INFORMATION__INIT;
  *message = init_value;
}
size_t vod__detector_information__get_packed_size
                     (const VOD__DetectorInformation *message)
{
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__detector_information__pack
                     (const VOD__DetectorInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__detector_information__pack_to_buffer
                     (const VOD__DetectorInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__DetectorInformation *
       vod__detector_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__DetectorInformation *)
     protobuf_c_message_unpack (&vod__detector_information__descriptor,
                                allocator, len, data);
}
void   vod__detector_information__free_unpacked
                     (VOD__DetectorInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vod__attribute__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Attribute, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr_class",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VOD__Attribute, has_class_case),
    offsetof(VOD__Attribute, attr_class),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VOD__Attribute, has_score_case),
    offsetof(VOD__Attribute, score),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__attribute__field_indices_by_name[] = {
  1,   /* field[1] = attr_class */
  2,   /* field[2] = score */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange vod__attribute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vod__attribute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Attribute",
  "Attribute",
  "VOD__Attribute",
  "VOD",
  sizeof(VOD__Attribute),
  3,
  vod__attribute__field_descriptors,
  vod__attribute__field_indices_by_name,
  1,  vod__attribute__number_ranges,
  (ProtobufCMessageInit) vod__attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__classification__field_descriptors[2] =
{
  {
    "det_class",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VOD__Classification, has_class_case),
    offsetof(VOD__Classification, det_class),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VOD__Classification, has_score_case),
    offsetof(VOD__Classification, score),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__classification__field_indices_by_name[] = {
  0,   /* field[0] = det_class */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange vod__classification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vod__classification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Classification",
  "Classification",
  "VOD__Classification",
  "VOD",
  sizeof(VOD__Classification),
  2,
  vod__classification__field_descriptors,
  vod__classification__field_indices_by_name,
  1,  vod__classification__number_ranges,
  (ProtobufCMessageInit) vod__classification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vod__detection__detection_status__enum_values_by_number[3] =
{
  { "UNTRACKED", "VOD__DETECTION__DETECTION_STATUS__UNTRACKED", 0 },
  { "TRACKED_UNCONFIDENT", "VOD__DETECTION__DETECTION_STATUS__TRACKED_UNCONFIDENT", 1 },
  { "TRACKED_CONFIDENT", "VOD__DETECTION__DETECTION_STATUS__TRACKED_CONFIDENT", 2 },
};
static const ProtobufCIntRange vod__detection__detection_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex vod__detection__detection_status__enum_values_by_name[3] =
{
  { "TRACKED_CONFIDENT", 2 },
  { "TRACKED_UNCONFIDENT", 1 },
  { "UNTRACKED", 0 },
};
const ProtobufCEnumDescriptor vod__detection__detection_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VOD.Detection.DetectionStatus",
  "DetectionStatus",
  "VOD__Detection__DetectionStatus",
  "VOD",
  3,
  vod__detection__detection_status__enum_values_by_number,
  3,
  vod__detection__detection_status__enum_values_by_name,
  1,
  vod__detection__detection_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor vod__detection__field_descriptors[10] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "top",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, right),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bottom",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, bottom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "det_class",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, det_class),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detection_status",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, detection_status),
    &vod__detection__detection_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__Detection, n_attributes),
    offsetof(VOD__Detection, attributes),
    &vod__attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classifications",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__Detection, n_classifications),
    offsetof(VOD__Detection, classifications),
    &vod__classification__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__detection__field_indices_by_name[] = {
  8,   /* field[8] = attributes */
  3,   /* field[3] = bottom */
  9,   /* field[9] = classifications */
  5,   /* field[5] = det_class */
  7,   /* field[7] = detection_status */
  4,   /* field[4] = id */
  0,   /* field[0] = left */
  2,   /* field[2] = right */
  6,   /* field[6] = score */
  1,   /* field[1] = top */
};
static const ProtobufCIntRange vod__detection__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 9 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor vod__detection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Detection",
  "Detection",
  "VOD__Detection",
  "VOD",
  sizeof(VOD__Detection),
  10,
  vod__detection__field_descriptors,
  vod__detection__field_indices_by_name,
  2,  vod__detection__number_ranges,
  (ProtobufCMessageInit) vod__detection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__event__field_descriptors[3] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(VOD__Event, action),
    &vod__event_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Event, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_ids",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(VOD__Event, n_object_ids),
    offsetof(VOD__Event, object_ids),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__event__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = object_id */
  2,   /* field[2] = object_ids */
};
static const ProtobufCIntRange vod__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vod__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Event",
  "Event",
  "VOD__Event",
  "VOD",
  sizeof(VOD__Event),
  3,
  vod__event__field_descriptors,
  vod__event__field_indices_by_name,
  1,  vod__event__number_ranges,
  (ProtobufCMessageInit) vod__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__scene__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(VOD__Scene, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detections",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__Scene, n_detections),
    offsetof(VOD__Scene, detections),
    &vod__detection__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__Scene, n_events),
    offsetof(VOD__Scene, events),
    &vod__event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__scene__field_indices_by_name[] = {
  1,   /* field[1] = detections */
  2,   /* field[2] = events */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange vod__scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vod__scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Scene",
  "Scene",
  "VOD__Scene",
  "VOD",
  sizeof(VOD__Scene),
  3,
  vod__scene__field_descriptors,
  vod__scene__field_indices_by_name,
  1,  vod__scene__number_ranges,
  (ProtobufCMessageInit) vod__scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__calibration__field_descriptors[3] =
{
  {
    "precision",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Calibration, precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recall",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Calibration, recall),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threshold",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Calibration, threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__calibration__field_indices_by_name[] = {
  0,   /* field[0] = precision */
  1,   /* field[1] = recall */
  2,   /* field[2] = threshold */
};
static const ProtobufCIntRange vod__calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vod__calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Calibration",
  "Calibration",
  "VOD__Calibration",
  "VOD",
  sizeof(VOD__Calibration),
  3,
  vod__calibration__field_descriptors,
  vod__calibration__field_indices_by_name,
  1,  vod__calibration__number_ranges,
  (ProtobufCMessageInit) vod__calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__object_class__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__ObjectClass, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VOD__ObjectClass, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calibrations",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__ObjectClass, n_calibrations),
    offsetof(VOD__ObjectClass, calibrations),
    &vod__calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attribute_type_ids",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(VOD__ObjectClass, n_attribute_type_ids),
    offsetof(VOD__ObjectClass, attribute_type_ids),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__object_class__field_indices_by_name[] = {
  3,   /* field[3] = attribute_type_ids */
  2,   /* field[2] = calibrations */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange vod__object_class__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vod__object_class__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.ObjectClass",
  "ObjectClass",
  "VOD__ObjectClass",
  "VOD",
  sizeof(VOD__ObjectClass),
  4,
  vod__object_class__field_descriptors,
  vod__object_class__field_indices_by_name,
  1,  vod__object_class__number_ranges,
  (ProtobufCMessageInit) vod__object_class__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__attribute_class__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__AttributeClass, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VOD__AttributeClass, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calibrations",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__AttributeClass, n_calibrations),
    offsetof(VOD__AttributeClass, calibrations),
    &vod__calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__attribute_class__field_indices_by_name[] = {
  2,   /* field[2] = calibrations */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange vod__attribute_class__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vod__attribute_class__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.AttributeClass",
  "AttributeClass",
  "VOD__AttributeClass",
  "VOD",
  sizeof(VOD__AttributeClass),
  3,
  vod__attribute_class__field_descriptors,
  vod__attribute_class__field_indices_by_name,
  1,  vod__attribute_class__number_ranges,
  (ProtobufCMessageInit) vod__attribute_class__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__attribute_type__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__AttributeType, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VOD__AttributeType, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__AttributeType, n_classes),
    offsetof(VOD__AttributeType, classes),
    &vod__attribute_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__attribute_type__field_indices_by_name[] = {
  2,   /* field[2] = classes */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange vod__attribute_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vod__attribute_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.AttributeType",
  "AttributeType",
  "VOD__AttributeType",
  "VOD",
  sizeof(VOD__AttributeType),
  3,
  vod__attribute_type__field_descriptors,
  vod__attribute_type__field_indices_by_name,
  1,  vod__attribute_type__number_ranges,
  (ProtobufCMessageInit) vod__attribute_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__detector_information__field_descriptors[2] =
{
  {
    "classes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__DetectorInformation, n_classes),
    offsetof(VOD__DetectorInformation, classes),
    &vod__object_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attribute_types",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__DetectorInformation, n_attribute_types),
    offsetof(VOD__DetectorInformation, attribute_types),
    &vod__attribute_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__detector_information__field_indices_by_name[] = {
  1,   /* field[1] = attribute_types */
  0,   /* field[0] = classes */
};
static const ProtobufCIntRange vod__detector_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vod__detector_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.DetectorInformation",
  "DetectorInformation",
  "VOD__DetectorInformation",
  "VOD",
  sizeof(VOD__DetectorInformation),
  2,
  vod__detector_information__field_descriptors,
  vod__detector_information__field_indices_by_name,
  1,  vod__detector_information__number_ranges,
  (ProtobufCMessageInit) vod__detector_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vod__event_action__enum_values_by_number[2] =
{
  { "EVENT_DELETE", "VOD__EVENT_ACTION__EVENT_DELETE", 0 },
  { "EVENT_CONNECT", "VOD__EVENT_ACTION__EVENT_CONNECT", 1 },
};
static const ProtobufCIntRange vod__event_action__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex vod__event_action__enum_values_by_name[2] =
{
  { "EVENT_CONNECT", 1 },
  { "EVENT_DELETE", 0 },
};
const ProtobufCEnumDescriptor vod__event_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VOD.EventAction",
  "EventAction",
  "VOD__EventAction",
  "VOD",
  2,
  vod__event_action__enum_values_by_number,
  2,
  vod__event_action__enum_values_by_name,
  1,
  vod__event_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
